package billingexpr

import (
	"math"
	"regexp"
	"strconv"
	"strings"
)

// visualPriceTermPattern matches the fixed unit-price terms emitted by the
// visual editor. Tier thresholds and request-rule multipliers are excluded.
var visualPriceTermPattern = regexp.MustCompile(`\b(p|c|cr|cc|cc1h|img|img_o|ai|ao)\s*\*\s*(-?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)`)

func normalizeDisplayMultiplier(multiplier float64) float64 {
	if math.IsNaN(multiplier) || math.IsInf(multiplier, 0) {
		return 1
	}
	if multiplier < 0 {
		return 0
	}
	return math.Round(multiplier*1e14) / 1e14
}

// ScaleVisualPriceTerms scales prices generated by the visual billing editor
// without changing tier conditions, expression versions, or request rules.
// Cache prices have their own multiplier because provider markup applies only
// to non-cache usage.
func ScaleVisualPriceTerms(expr string, nonCacheMultiplier, cacheMultiplier float64) string {
	expr = strings.TrimSpace(expr)
	if expr == "" {
		return ""
	}
	nonCacheMultiplier = normalizeDisplayMultiplier(nonCacheMultiplier)
	cacheMultiplier = normalizeDisplayMultiplier(cacheMultiplier)
	if nonCacheMultiplier == 1 && cacheMultiplier == 1 {
		return expr
	}

	// Request rules after ||| are multipliers over the evaluated result, not
	// unit prices. Keep them byte-for-byte unchanged.
	billingPart, requestRules := expr, ""
	if idx := strings.Index(billingPart, "|||"); idx >= 0 {
		requestRules = billingPart[idx:]
		billingPart = billingPart[:idx]
	}
	billingPart = visualPriceTermPattern.ReplaceAllStringFunc(billingPart, func(term string) string {
		parts := visualPriceTermPattern.FindStringSubmatch(term)
		if len(parts) != 3 {
			return term
		}
		price, err := strconv.ParseFloat(parts[2], 64)
		if err != nil {
			return term
		}
		multiplier := nonCacheMultiplier
		switch parts[1] {
		case "cr", "cc", "cc1h":
			multiplier = cacheMultiplier
		}
		price = math.Round(price*multiplier*1e14) / 1e14
		return parts[1] + " * " + strconv.FormatFloat(price, 'f', -1, 64)
	})
	return billingPart + requestRules
}
