package controller

import (
	"strings"

	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/model"
	"github.com/QuantumNous/new-api/pkg/billingexpr"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/setting/ratio_setting"

	"github.com/gin-gonic/gin"
)

func providerPricingRatio(rule model.ProviderModelPricing) float64 {
	if rule.Ratio == 0 {
		return 1
	}
	return rule.Ratio
}

// scaleBillingExprForDisplay scales the fixed unit-price terms generated by
// the visual editor without changing tier conditions or request multipliers.
func scaleBillingExprForDisplay(expr string, ioMultiplier, cacheMultiplier float64) string {
	return billingexpr.ScaleVisualPriceTerms(expr, ioMultiplier, cacheMultiplier)
}

func applyProviderPricingRule(item model.Pricing, rule model.ProviderModelPricing, importPriceRatio float64, cacheImportRatio float64) model.Pricing {
	if importPriceRatio <= 0 {
		importPriceRatio = 1
	}
	if cacheImportRatio <= 0 {
		// 未单独配置缓存折扣时，缓存按主站原价展示，不跟随输入输出折扣
		cacheImportRatio = 1
	}
	item.ModelName = rule.PublicModelName
	// 主站原始倍率 M：缓存展示反算需要（缓存价 = M × 原缓存倍率 × 缓存折扣）
	originalModelRatio := item.ModelRatio
	item.ModelRatio *= importPriceRatio
	item.ModelPrice *= importPriceRatio
	if len(item.ResolutionPrices) > 0 {
		prices := make(map[string]float64, len(item.ResolutionPrices))
		for resolution, price := range item.ResolutionPrices {
			prices[resolution] = price * importPriceRatio
		}
		item.ResolutionPrices = prices
	}

	if rule.PricingType == model.ProviderPricingTypeDelta {
		item.ModelRatio += rule.DeltaModelRatio
		item.ModelPrice += rule.DeltaModelPrice
		for resolution, price := range item.ResolutionPrices {
			item.ResolutionPrices[resolution] = price + rule.DeltaModelPrice
		}
		if item.BillingMode == "tiered_expr" && strings.TrimSpace(item.BillingExpr) != "" {
			item.BillingExpr = scaleBillingExprForDisplay(item.BillingExpr, importPriceRatio, cacheImportRatio)
			item.ProviderPricingType = model.ProviderPricingTypeDelta
			item.ProviderDeltaModelRatio = rule.DeltaModelRatio
		}
	} else {
		ratio := providerPricingRatio(rule)
		item.ModelRatio *= ratio
		item.ModelPrice *= ratio
		for resolution, price := range item.ResolutionPrices {
			item.ResolutionPrices[resolution] = price * ratio
		}
		if item.BillingMode == "tiered_expr" && strings.TrimSpace(item.BillingExpr) != "" {
			item.BillingExpr = scaleBillingExprForDisplay(item.BillingExpr, importPriceRatio*ratio, cacheImportRatio)
			item.ProviderPricingType = model.ProviderPricingTypeRatio
		}
	}
	if item.ModelRatio < 0 {
		item.ModelRatio = 0
	}
	if item.ModelPrice < 0 {
		item.ModelPrice = 0
	}
	// 缓存展示反算：缓存价不受服务商加价影响，展示为 主站缓存价 × 缓存折扣。
	// 前端按 展示ModelRatio × CacheRatio_display 计算缓存单价，因此
	// CacheRatio_display = 原值 × 缓存折扣 × M / 展示ModelRatio
	// （比例模式因子即 缓存折扣/(import×加价倍率)，与 M 无关；差价模式下
	// 展示ModelRatio = M×import+delta，因子随模型基础倍率不同而不同）。
	// 倍率未显式配置（nil）时保持为空；缓存折扣只换算主站已配置的价格项，
	// 不应在服务商模型广场创建主站不存在的价格摘要项。
	// 展示倍率非正（免费/按次模型）时无法反算，保持原值。
	// 注意：GetPricing 返回的是共享缓存切片，CacheRatio/CreateCacheRatio 是
	// 指向缓存本体的指针——禁止通过指针原地修改（否则缓存窗口内每次请求都会
	// 累乘一次，表现为"刷新一次缓存价格翻倍一次"），必须读取值后新建指针。
	if item.BillingMode != "tiered_expr" {
		if cacheRatioFactor := service.ProviderDisplayCacheFactor(originalModelRatio, item.ModelRatio, cacheImportRatio); cacheRatioFactor != 1 {
			if item.CacheRatio != nil {
				cacheRatio := *item.CacheRatio * cacheRatioFactor
				item.CacheRatio = &cacheRatio
			}

			if item.CreateCacheRatio != nil {
				createCacheRatio := *item.CreateCacheRatio * cacheRatioFactor
				item.CreateCacheRatio = &createCacheRatio
			}
		}
	}
	return item
}

func applyProviderPricingView(providerId int, pricing []model.Pricing) []model.Pricing {
	if providerId == 0 || len(pricing) == 0 {
		return pricing
	}
	base := make(map[string]model.Pricing, len(pricing))
	for _, item := range pricing {
		base[item.ModelName] = item
	}
	var rules []model.ProviderModelPricing
	if err := model.DB.Where("provider_id = ? AND enabled = ?", providerId, true).Find(&rules).Error; err != nil {
		common.SysLog("failed to get provider pricing: " + err.Error())
		return []model.Pricing{}
	}
	importPriceRatio := 1.0
	cacheImportRatio := 0.0
	var cfg model.ProviderConfig
	if err := model.DB.Select("import_price_ratio, import_cache_price_ratio").Where("provider_id = ?", providerId).First(&cfg).Error; err == nil && cfg.ImportPriceRatio > 0 {
		importPriceRatio = cfg.ImportPriceRatio
		cacheImportRatio = cfg.ImportCachePriceRatio
	}
	result := make([]model.Pricing, 0, len(rules))
	for _, rule := range rules {
		item, ok := base[rule.BaseModelName]
		if !ok {
			continue
		}
		result = append(result, applyProviderPricingRule(item, rule, importPriceRatio, cacheImportRatio))
	}
	return result
}

func filterPricingByUsableGroups(pricing []model.Pricing, usableGroup map[string]string) []model.Pricing {
	if len(pricing) == 0 {
		return pricing
	}
	if len(usableGroup) == 0 {
		return []model.Pricing{}
	}

	filtered := make([]model.Pricing, 0, len(pricing))
	for _, item := range pricing {
		if common.StringsContains(item.EnableGroup, "all") {
			filtered = append(filtered, item)
			continue
		}
		for _, group := range item.EnableGroup {
			if _, ok := usableGroup[group]; ok {
				filtered = append(filtered, item)
				break
			}
		}
	}
	return filtered
}

func getPricingVisibilityContext(c *gin.Context) (map[string]string, map[string]float64, []string) {
	usableGroup := map[string]string{}
	groupRatio := map[string]float64{}
	for s, f := range ratio_setting.GetGroupRatioCopy() {
		groupRatio[s] = f
	}
	var group string
	if userId, exists := c.Get("id"); exists {
		user, err := model.GetUserCache(userId.(int))
		if err == nil {
			group = user.Group
			for g := range groupRatio {
				ratio, ok := ratio_setting.GetGroupGroupRatio(group, g)
				if ok {
					groupRatio[g] = ratio
				}
			}
		}
	}

	usableGroup = service.GetUserUsableGroups(group)
	for group := range ratio_setting.GetGroupRatioCopy() {
		if _, ok := usableGroup[group]; !ok {
			delete(groupRatio, group)
		}
	}
	return usableGroup, groupRatio, service.GetUserAutoGroup(group)
}

// getMarketplaceVisiblePricingForUserGroup 按指定用户分组计算主站市场可见的定价列表。
// 不依赖 *gin.Context，供后台自动同步（goroutine）使用
func getMarketplaceVisiblePricingForUserGroup(userGroup string) []model.Pricing {
	pricing := model.GetPricing()
	usableGroup := service.GetUserUsableGroups(userGroup)
	return filterPricingByUsableGroups(pricing, usableGroup)
}

func getMarketplaceVisiblePricing(c *gin.Context) []model.Pricing {
	pricing := model.GetPricing()
	usableGroup, _, _ := getPricingVisibilityContext(c)
	return filterPricingByUsableGroups(pricing, usableGroup)
}

func GetPricing(c *gin.Context) {
	pricing := model.GetPricing()
	providerId := common.GetContextKeyInt(c, constant.ContextKeyProviderId)
	pricing = applyProviderPricingView(providerId, pricing)
	usableGroup, groupRatio, autoGroups := getPricingVisibilityContext(c)
	pricing = filterPricingByUsableGroups(pricing, usableGroup)

	c.JSON(200, gin.H{
		"success":            true,
		"data":               pricing,
		"vendors":            model.GetVendors(),
		"group_ratio":        groupRatio,
		"usable_group":       usableGroup,
		"supported_endpoint": model.GetSupportedEndpointMap(),
		"auto_groups":        autoGroups,
		"pricing_version":    "b2c5fbb11278d477f8141196fd56208a",
	})
}

func ResetModelRatio(c *gin.Context) {
	defaultStr := ratio_setting.DefaultModelRatio2JSONString()
	err := model.UpdateOption("ModelRatio", defaultStr)
	if err != nil {
		c.JSON(200, gin.H{
			"success": false,
			"message": err.Error(),
		})
		return
	}
	err = ratio_setting.UpdateModelRatioByJSONString(defaultStr)
	if err != nil {
		c.JSON(200, gin.H{
			"success": false,
			"message": err.Error(),
		})
		return
	}
	c.JSON(200, gin.H{
		"success": true,
		"message": "重置模型倍率成功",
	})
}
